const recipeApp = {state: {tab: 'discover', cuisine: 'all', category: null, recipes: [], favs: JSON.parse(localStorage.getItem('favorites')) || []}, dom: {searchForm: document.getElementById('searchForm'), searchInput: document.getElementById('searchInput'), searchError: document.getElementById('searchError'), cuisineFilters: document.getElementById('cuisineFilters'), categoryFilters: document.getElementById('categoryFilters'), tabs: document.querySelectorAll('.tab'), recipeGrid: document.getElementById('recipeGrid'), loading: document.getElementById('loading'), errorState: document.getElementById('errorState'), emptyState: document.getElementById('emptyState'), favCount: document.getElementById('favCount'), modal: document.getElementById('recipeModal')}};
async function startApp() {try {showLoad(); const r = await getInitialRecipes(); recipeApp.state.recipes = r; showRecipes(r); hideLoad(); updateCount();} catch (e) {console.error(e); hideLoad(); showErr('Failed to load');}}
function showRecipes(recipes) {recipeApp.dom.recipeGrid.innerHTML = ''; hideElement(recipeApp.dom.emptyState); hideElement(recipeApp.dom.errorState); if (!recipes || recipes.length === 0) {showElement(recipeApp.dom.emptyState); return;} recipes.forEach(r => {const isFav = recipeApp.state.favs.some(f => f.idMeal === r.idMeal); recipeApp.dom.recipeGrid.appendChild(buildCard(r, isFav));});}
function buildCard(recipe, isFav) {const c = document.createElement('div'); c.className = 'recipe-card'; c.innerHTML = `<div class="recipe-image-wrapper"><img src="${recipe.strMealThumb}" alt="${recipe.strMeal}" class="recipe-image"><span class="recipe-cuisine">${recipe.strArea}</span><button class="favorite-btn ${isFav ? 'active' : ''}" data-id="${recipe.idMeal}">${isFav ? '❤️' : '🤍'}</button></div><div class="recipe-info"><h3 class="recipe-title">${recipe.strMeal}</h3><div class="recipe-meta"><span class="recipe-category">${recipe.strCategory}</span></div></div>`; c.querySelector('.recipe-image-wrapper').addEventListener('click', () => showModal(recipe)); c.querySelector('.favorite-btn').addEventListener('click', (e) => {e.stopPropagation(); toggleFav(recipe);}); return c;}
function showModal(recipe) {const ings = []; for (let i = 1; i <= 20; i++) {const ing = recipe[`strIngredient${i}`]; const m = recipe[`strMeasure${i}`]; if (ing && ing.trim()) ings.push({ing, m});} recipeApp.dom.modal.innerHTML = `<div class="modal-content"><div class="modal-header"><img src="${recipe.strMealThumb}" alt="${recipe.strMeal}" class="modal-image"><button class="modal-close" onclick="hideModal()">×</button></div><div class="modal-body"><h2 class="modal-title">${recipe.strMeal}</h2><div class="modal-meta"><span class="modal-tag cuisine">${recipe.strArea}</span><span class="modal-tag">${recipe.strCategory}</span></div><div class="modal-section"><h3>Ingredients</h3><div class="ingredients-grid">${ings.map(({ing, m}) => `<div class="ingredient-item"><span class="ingredient-check"></span><span>${m} ${ing}</span></div>`).join('')}</div></div><div class="modal-section"><h3>Instructions</h3><p class="instructions">${recipe.strInstructions}</p></div>${recipe.strYoutube ? `<div class="modal-section"><a href="${recipe.strYoutube}" target="_blank" class="video-link">Watch Video</a></div>` : ''}</div></div>`; recipeApp.dom.modal.classList.add('show');}
function hideModal() {recipeApp.dom.modal.classList.remove('show');}
function toggleFav(recipe) {const idx = recipeApp.state.favs.findIndex(f => f.idMeal === recipe.idMeal); if (idx > -1) {recipeApp.state.favs.splice(idx, 1);} else {recipeApp.state.favs.push(recipe);} localStorage.setItem('favorites', JSON.stringify(recipeApp.state.favs)); updateCount(); if (recipeApp.state.tab === 'favorites') {showRecipes(recipeApp.state.favs);} else {showRecipes(recipeApp.state.recipes);}}
function updateCount() {recipeApp.dom.favCount.textContent = `(${recipeApp.state.favs.length})`;} 
async function doSearch(e) {e.preventDefault(); const q = recipeApp.dom.searchInput.value.trim(); if (q.length < 2) {recipeApp.dom.searchInput.classList.add('error'); recipeApp.dom.searchError.classList.add('show'); return;} recipeApp.dom.searchInput.classList.remove('error'); recipeApp.dom.searchError.classList.remove('show'); try {showLoad(); const r = await searchRecipes(q); recipeApp.state.recipes = r; showRecipes(r); hideLoad();} catch (e) {console.error(e); hideLoad(); showErr('Search failed');}}
async function filterCuisine(cuisine) {recipeApp.state.cuisine = cuisine; recipeApp.state.category = null; document.querySelectorAll('#cuisineFilters .filter-btn').forEach(b => {b.classList.toggle('active', b.dataset.cuisine === cuisine);}); document.querySelectorAll('#categoryFilters .filter-btn').forEach(b => {b.classList.remove('active');}); try {showLoad(); const r = await filterByCuisine(cuisine); recipeApp.state.recipes = r; showRecipes(r); hideLoad();} catch (e) {console.error(e); hideLoad(); showErr('Filter failed');}}
async function filterCat(category) {recipeApp.state.category = category; document.querySelectorAll('#categoryFilters .filter-btn').forEach(b => {b.classList.toggle('active', b.dataset.category === category);}); try {showLoad(); const r = await filterByCategory(category); recipeApp.state.recipes = r; showRecipes(r); hideLoad();} catch (e) {console.error(e); hideLoad(); showErr('Filter failed');}}
function switchTab(tab) {recipeApp.state.tab = tab; recipeApp.dom.tabs.forEach(t => {t.classList.toggle('active', t.dataset.tab === tab);}); if (tab === 'favorites') {showRecipes(recipeApp.state.favs);} else {showRecipes(recipeApp.state.recipes);}}
function showLoad() {recipeApp.dom.loading.classList.add('show'); recipeApp.dom.recipeGrid.style.display = 'none';}
function hideLoad() {recipeApp.dom.loading.classList.remove('show'); recipeApp.dom.recipeGrid.style.display = 'grid';}
function showErr(msg) {recipeApp.dom.errorState.classList.add('show'); recipeApp.dom.errorState.querySelector('p').textContent = msg;}
recipeApp.dom.searchForm.addEventListener('submit', doSearch);
recipeApp.dom.searchInput.addEventListener('input', () => {if (recipeApp.dom.searchInput.value.trim().length >= 2) {recipeApp.dom.searchInput.classList.remove('error'); recipeApp.dom.searchError.classList.remove('show');}});
recipeApp.dom.cuisineFilters.addEventListener('click', (e) => {if (e.target.classList.contains('filter-btn')) {filterCuisine(e.target.dataset.cuisine);}});
recipeApp.dom.categoryFilters.addEventListener('click', (e) => {if (e.target.classList.contains('filter-btn')) {filterCat(e.target.dataset.category);}});
recipeApp.dom.tabs.forEach(tab => {tab.addEventListener('click', () => switchTab(tab.dataset.tab));});
recipeApp.dom.modal.addEventListener('click', (e) => {if (e.target === recipeApp.dom.modal) hideModal();});
startApp();